### ISSUE TITLE
Adding rdfp_version field

### ISSUE THREAD

**Issue by 0x4D31** [yahoo/rdfp#2]
It would be good to add a rdfp_version field for tracking the future changes in rdfp composition (just like the hasshVersion in hassh bro script: https://github.com/salesforce/hassh/blob/master/bro/hassh.bro#L24).
e.g. I was thinking about adding clientBuild from the Client Core Data to rdfp v1.0 (need to double check the results based on my new pcap dataset).

**Comment by neslog** [comment]
Agreed with the version field.  

I looked at clientBuild, agreed it may be worth it. Let me know what you decide from your testing.
